config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#index'
  
  get 'new', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'send_coupa', to: 'items#send_coupa'
  post 'shopping_cart', to: 'items#shopping_cart'
  
  get 'cart_catalogue', to: 'items#cart_catalogue'
  get ':id/show', to: 'items#view_more', as: 'view_more'

  put 'decrement', to: 'items#decrement_quantity'
  put 'increment', to: 'items#increment_quantity'

  # delete 'delete_item', to: 'items#delete_item'
  
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authorize, :set_cart
  
  def index
    @items = current_user.items(session[:user])["PurchaseableItems"]
  end

  def show
    @cart_items = session[:CartItems]
    @xml = current_user.return_to_coupa( session[:user], @cart_items["ShoppingCartItems"]) if @cart_items["ShoppingCartItems"].present?

    respond_to do |format|
      format.js { render layout: false } 
      # Add this line to you respond_to block
    end
  end

  def create
    @cart_item = current_user.create_cart_item(items_params)
    render :json => { error: false, data: @cart_item }
  end

  def edit
  end

  def cart_catalogue
    @cart_items = session[:CartItems]
    @xml = current_user.return_to_coupa( session[:user], @cart_items["ShoppingCartItems"]) if @cart_items["ShoppingCartItems"].present?
  end

  def view_more
    @cart_items = session[:CartItems]
    @item = current_user.item_get(params, session[:ShoppingCartID])
    @item["FileGUID"] = params[:file]
  end
  
  def increment_quantity
    @cart_item = current_user.update_cart_item(items_update)
    render :json => { error: false, data: @cart_item }
  end

  def decrement_quantity
    @cart_item = current_user.update_cart_item(items_update)
    render :json => { error: false, data: @cart_item }
  end

  def destroy
    @cart_item = current_user.delete_cart_item(items_params_delete)
    render :json => { error: false, data: @cart_item }
  end

  private

  def items_params
    params.permit(:shoppingCartID, :contractItemID, :quantity)
  end

  def items_params_delete
    params.permit(:shoppingCartID, :shoppingCartItemID)
  end

  def items_update
    params.permit(:ShoppingCartID, :shoppingCartItemID, :quantity)
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_show.html.erb
<% total = 0 %>

<div class="cart__metaheader" style="padding: 0 .3rem;">
    <%= link_to(cart_catalogue_path) do %>
        <i class="fa fa-long-arrow-left"></i> View Complete Shopping Cart
    <% end %>
</div>

<% if @cart_items["ShoppingCartItems"].present? %>

    <div class="cart__header" style="padding: 0 .3rem;">
        <h2>SHOPPING CART</h2>
        <p><%= @cart_items["recordcount"] %> Item(s)</p>
    </div>

    <div id="items__wrapper" class="items__wrapper">
        <% @cart_items["ShoppingCartItems"].each do |cart_item| %>
            <% quantity = cart_item["Quantity"] %>

            <div id="item_wrapper_<%= cart_item["ContractItemID"] %>" class="item__content">
                <div class="item__description">
                    <p><%= cart_item["Name"] %></p>
                </div>
                <div class="item__quantity">
                    <button id="decrement"> - </button>
                    <input type="number" class="quantity-input" size="4" step="1" min="1" max="" value="<%= quantity %>" readonly>
                    <button id="increment"> + </button>
                </div>
                <div class="item__price">
                    <% quantity_total = cart_item["UnitPrice"].to_f * quantity %>
                    <h4>R <%= '%.2f' % quantity_total %></h4>
                    <% total += quantity_total %>
                </div>
                <div class="shopping-cart__item-delete-btn">
                    <%# link_to("Delete", item_path, method: :delete, class: "delete_item", id: "delete-item", remote: true, data: { turbolinks: false, shoppingCart: session[:ShoppingCart], itemID: cart_item["ContractItemID"]} ) %>
                </div>
            </div>
        <% end %>
    </div>

    <div class="item__subtotal">
        <h4>Subtotal:</h4>
        <h3><%= '%.2f' % total %></h3>
    </div>

    <form id="cxml_form" method="POST" action="<%= session[:user]["ReturnURL"] %>" enctype="application/x-www-form-urlencoded">
        <input id="cXML-urlencoded" type="hidden" name="cXML-urlencoded" value="<%= @xml.html_safe %>" >
        <div class="item__checkout"> 
           <input type="submit" id="checkout" value="Return To Coupa">
        </div>
    </form>

<% else %>
    <div style="color:#6a6a6a; display: flex; padding: 5em 0; justify-content: center;" id="items__wrapper" class="items__wrapper">
        <h2>NO ITEMS IN THE CART</h2>
    </div>   
<% end %>

<%= javascript_pack_tag 'items' %>

app/views/items/cart_catalogue.html.erb
<% total = 0 %>

<div class="shopping-cart">
    <div class="shopping-cart__container">
        <div class="shopping-cart__wrapper">

            <div class="shopping-cart__items-container">

                <div class="shopping-cart__header--wrapper">
                    <div class="shopping-cart__header shopping-cart__header--white">
                        <h1>SHOPPING CART</h1>
                        <h1><%= @cart_items["recordcount"] %> ITEMS</h1>
                    </div>
                </div>

                <div class="shopping-cart__items--wrapper">                     
                    <% if session[:CartItems]["ShoppingCartItems"].present? %>
                                
                        <% @cart_items["ShoppingCartItems"].each do |cart_item| %>
                            <% quantity = cart_item["Quantity"] %>

                            <div id="shopping-cart__item--<%= cart_item["ID"] %>" class="shopping-cart__item">
                                <div class="shopping-cart__item-image">
                                    <img src="" alt="">
                                </div>
                                <div class="shopping-cart__item-name">
                                    <p><%= cart_item["Name"] %></p>
                                </div>
                                <div id="shopping-cart__item-quantity--<%= cart_item["ID"] %>" class="shopping-cart__item-quantity">
                                    <%= button_tag( " - ", class: "decrement", id: "decrement", data: { shoppingCart: session[:ShoppingCart], shoppingCartItemID: cart_item["ID"] } ) %>
                                        <input type="number" value="<%= quantity %>" id="quantity-input--<%= cart_item["ID"] %>" class="quantity-input" readonly>
                                    <%= button_tag(" + ", class: "increment", id: "increment", data: { shoppingCart: session[:ShoppingCart], shoppingCartItemID: cart_item["ID"] }) %>
                                </div>
                                <div class="shopping-cart__item-price">
                                    <% quantity_total = cart_item["UnitPrice"].to_f * quantity %>
                                    <h3>R <%= '%.2f' % quantity_total %></h3>
                                    <% total = total + quantity_total %>
                                </div>
                                <div class="shopping-cart__item-delete-btn">
                                    <%= button_tag(class: "remove_link", id: "remove-link", data: { shoppingCart: session[:ShoppingCart], shoppingCartItemID: cart_item["ID"] } ) do %>
                                        <i class="fa fa-remove"></i>
                                    <% end %>
                                </div>
                            </div>
                        <% end %>
                    <% end %>
                </div>

                <div class="shopping-cart__continue">
                    <%= link_to(items_path, class: "shopping-cart__continue-btn") do %>
                        <i class="fa fa-long-arrow-left"></i> Continue Shopping
                    <% end %>
                </div>

            </div>

            <div class="shopping-cart__order-summary">
                <div class="shopping-cart__header--wrapper">
                    <div class="shopping-cart__header shopping-cart__header--blue">
                        <h1>ORDER SUMMARY</h1>
                    </div>
                </div>

                <div class="item__subtotal">
                    <h4>Subtotal:</h4>
                    <h3><%= '%.2f' % total %></h3>
                </div>

                <form id="cxml_form" method="POST" action="<%= session[:user]["ReturnURL"] %>" enctype="application/x-www-form-urlencoded">
                    <input id="cXML-urlencoded" type="hidden" name="cXML-urlencoded" value="<%= @xml.html_safe %>" >
                    <div class="item__checkout"> 
                        <input type="submit" id="checkout" value="Return To Coupa">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<%= javascript_pack_tag 'items' %>

app/views/items/create.html.erb
<%# @WEE %>


// function delete_in_cart(button, shoppingCartID, itemID){
//   var requestURL = "/items/" + itemID

//   $.ajax({
//       url: requestURL,
//       method: "DELETE",
//       data: { shoppingCartID: shoppingCartID, contractItemID: itemID },
//       success: function(resp){
//           if (resp.error) console.log(resp.message)
//           else{
//               console.log(resp)
//               $("#item_wrapper_" + itemID)
//           }
//       },
//       async: false
//   });
// }

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

<%= @cart_item %>

app/views/items/edit.html.erb
<h1>Items#edit</h1>
<p>Find me in app/views/items/edit.html.erb</p>

app/views/items/index.html.erb
<%= render 'header' %>

<section class="search-and-cart">
    <div class="search-and-cart__container">
        <div class="search-wrapper">
            <input type="text" placeholder="Searching for...">
        </div>
    </div>
</section>

<section class="catalogue">
    <% if @items.present? %>
        <div class="catalogue__products">
            <div class="catalogue__products-items">
                <% @items.each do |item| %>
                    <div class="item">
                        <div class="item__image">
                            <img src="https://suppliersite.azure-api.net/file?FileGUID=<%= item["FileGUID"] %>" alt="">
                        </div>
                        <div class="item__description">
                            <div class="description__name">
                                <h3><%= item["Name"] %></h3>
                            </div>
                            <div class="description__information">
                                <p><%= item["Description"] %></p>
                            </div>
                        </div>
        
                        <div class="item__price-btns-wrapper">
                            <div class="price">
                                <h4>R<%= '%.2f' % item["Price"] %></h4>
                            </div>
                            <div class="btns">
                                <%= link_to('View More', view_more_path(id: item["contractitemid"], file: item["FileGUID"]), id: "view-more") %>
                                <%= button_tag("Add To Cart", class: "add_to_cart", id: "add-to-cart", data: { user: session[:user], shoppingCart: session[:ShoppingCart], itemID: item["contractitemid"], disable_with: "<i class='fa fa-spinner fa-spin' style='color:#00086B;'></i>wait..".html_safe}) %>
                            </div>
                        </div>
                    </div>
                <% end %>
            </div>

            <div id="shopping__cart" class="shopping__cart" style="border-top: 1px solid #eeeeee; padding: 1rem 0;">
                 
            </div>
        </div>
    <% else %>
        <div class="no-items" style="margin-top: 5rem; font-size: 4rem; color: #6a6a6a;">
            <p style="color: #6a6a6a;">NO ITEMS</p>
        </div>
    <% end %>
</section>

<%= javascript_pack_tag 'items' %>
<%= javascript_pack_tag 'catalogue' %>

app/views/items/new.html.erb
<h1>Items#new</h1>
<p>Find me in app/views/items/new.html.erb</p>

app/views/items/send_coupa.html.erb
<%= @xml %>

app/views/items/shopping_cart.html.erb
<%= @response %>

app/views/items/show.html.erb
<h1>Items#show</h1>
<p>Find me in app/views/items/show.html.erb</p>

app/views/items/show.js.erb
$("#shopping__cart")
    .html("<%= escape_javascript(render partial: 'items/show', locals: { cart_items: @cart_items }) %>");

$('#decrement').on( "click", function(){
    qnty = parseInt($('.quantity-input').val())

    if (qnty > 1){
        $('.quantity-input').val(qnty - 1)
    }
});

$('#increment').on( "click", function(){
    qnty = parseInt($('.quantity-input').val())
    $('.quantity-input').val(qnty + 1)
});

function show_error(message) {
    var error = `<div class="alert alert-danger"> ${message} </div>`;
    $(".page-breadcrumb").after($(error));
    setTimeout(function () { $(".alert").remove(); }, 5000);
}

$('.delete_item').click(function(e){
    e.preventDefault()

    var shoppingCart = $(this).data("shoppingcart");
    var shoppingCartID = shoppingCart["ID"];
    var itemID = $(this).data("itemid")

    console.log("ITEM -------------------- ")
    console.log(shoppingCart)
    console.log(shoppingCartID)
    console.log(itemID)

    delete_in_cart(this, shoppingCartID, itemID);
});

function delete_in_cart(button, shoppingCartID, itemID){
    var requestURL = "/items/" + itemID

    $.ajax({
        url: requestURL,
        method: "DELETE",
        data: { shoppingCartID: shoppingCartID, contractItemID: itemID },
        success: function(resp){
            if (resp.error) console.log(resp.message)
            else{
                console.log(resp)
                $("#item_wrapper_" + itemID)
            }
        },
        async: false
    });
}

app/views/items/update.html.erb
<h1>Items#update</h1>
<p>Find me in app/views/items/update.html.erb</p>

app/views/items/view_more.html.erb
<%= render 'header' %>

<div class="breadcrumbs">
    <ul>
        <li class="breadcrumbs__item">
            <%= link_to 'Items', items_path, class: "breadcrumbs__link" %>
        </li>
        <li class="breadcrumbs__item"><p class="breadcrumbs__link breadcrumbs__link--active"><%= @item["BuyerItem"]["ItemName"] %></p></li>
    </ul>
</div>

<div class="view__more-container">
    <div class="view__more-wrapper">
        <div class="view__more-image">
            <img src="https://suppliersite.azure-api.net/file?FileGUID=<%= @item["FileGUID"] %>" alt="IMAGE">
        </div>
        <div class="view__more-description">
            <div class="description__name">
                <h1><%= @item["BuyerItem"]["ItemName"] %></h1>
            </div>
            <div class="description__total-price">
                <h4>R <%= '%.2f' % @item["Price"] %></h4>
            </div>
            <div class="description__content">
                <p><%= @item["BuyerItem"]["Description"] %></p>
            </div>
            <div class="description__total">
                <p>Quantity:</p>
                <div class="description__total-quantity">
                    <button id="decrement"> - </button>
                    <input type="number" class="quantity-input" size="4" step="1" min="1" max="" value="1" readonly>
                    <button id="increment"> + </button>
                </div>
            </div>
            <div class="description__add-to-cart">
                <%= link_to('BACK', items_path) %>
                <%= button_tag("ADD TO CART", class: "add_to_cart", id: "add-to-cart", data: { user: session[:user], shoppingCart: session[:ShoppingCart], itemID: @item["ContractItemID"], disable_with: "<i class='fa fa-spinner fa-spin' style='color:#00086B;'></i>wait..".html_safe}) %>
            </div>
        </div>
    </div>

    <div id="shopping__cart" class="shopping__cart" style="border-top: 1px solid #eeeeee; padding: 1rem 0;">
                 
    </div>
    
</div>

<%= javascript_pack_tag 'items' %>
<%= javascript_pack_tag 'catalogue' %>

app/views/items/view_more.js.erb
$("#shopping__cart")
    .html("<%= escape_javascript(render partial: 'items/show', locals: { cart_items: @cart_items }) %>");