config/routes.rb
Rails.application.routes.draw do
  root to: 'sessions#index'
  
  get 'new', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'send_coupa', to: 'items#send_coupa'
  post 'shopping_cart', to: 'items#shopping_cart'
  
  get 'cart_catalogue', to: 'items#cart_catalogue'
  get ':id/show', to: 'items#view_more', as: 'view_more'

  put 'decrement', to: 'items#decrement_quantity'
  put 'increment', to: 'items#increment_quantity'

  # delete 'delete_item', to: 'items#delete_item'
  
  resources :items
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :authorize
    helper_method :current_user
    helper_method :logged_in?

    rescue_from ActionController::InvalidAuthenticityToken, with: :user_not_authorized
    
    def user_not_authorized
        redirect_to root_path
    end

    def logged_in?
        !current_user.nil?
    end

    def redirect_if_logged_in?
        redirect_to order_index_path if logged_in?
    end

    def set_cart
        session[:CartItems] = current_user.get_cart_items(session[:ShoppingCartID])
        session[:ShoppingCartNoOfItems] = session[:CartItems]["recordcount"]
    end

    def current_user
        @current_user ||= begin
            User.new(session[:user]) if session[:user]
        end
    end

    def authorize
        return if logged_in?
    end

    def set_current_user(user)
        session[:user] = user # Unchanged sessions
        time = Time.now
        needByDate = "#{time.year}-#{time.month + 2}-#{time.day}"
        cart_params = { UserID: user["userid"], NeedByDate: needByDate, Comments: "" }

        session[:ShoppingCart] = current_user.create_cart(cart_params) # Once, Unchanged
        session[:ShoppingCartID] = session[:ShoppingCart]["ID"] # Unchanged

        session[:ShoppingCartNoOfItems] = "0"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_header.html.erb
<header>
    <div class="header__row">
        <div class="header__logo">
            <h1><a href="<%= items_path %>">SCP</a></h1>
        </div>
        <div class="header__navigation-links">
            <div id="navigation__cart" class="navigation__cart">

                <%= link_to item_path(1), id: "add-to-cart", remote: true, style: "padding: .5em;" do %>
                    <i class="fa fa-shopping-cart"></i>
                <% end %>

                <p class="cart-quantity"><%= session[:ShoppingCartNoOfItems] %></p>
            </div>

            <div id="navigation__profile" class="navigation__profile">
                <div class="content">
                    <p><%= session[:user]["name"] %></p> <i class="fa fa-user"></i>
                </div>
            </div>

            <div id="navigation__modal-menu" class="navigation__modal-menu">
                <div class="menu-name">
                    <h3>ACCOUNT</h3>
                </div>
                <div class="menu-links">
                    <ul>
                        <li><a class="menu-links--profile" href="javascript:void(0)">PROFILE</a></li>
                        <li><%= link_to 'LOGOUT', logout_path, :method => :delete, :class => 'logout', :data => { :confirm => 'Are you sure?'} %></li>
                    </ul>
                </div>
            </div> 

        </div>
    </div>
</header>

<%= javascript_pack_tag 'header' %>